sudo: required
dist: trusty
language: cpp

compiler: gcc

before_install:
# -  sudo apt-get remove binutils-arm-none-eabi gcc-arm-none-eabi
 - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y # -qq is for travis CI
 - sudo apt-get update
 - sudo apt-get install gcc-arm-embedded u-boot-tools libboost1.55-all-dev -y

before_script:
 - git clone https://github.com/ev3rt-git/ev3rt-hrp2/
 - cd ev3rt-hrp2
 - git submodule init
 - git submodule update
 - cd ..
 - git clone https://github.com/RoboticsBrno/RB-ev3rt-hrp2-sdk
 - rm -rf ev3rt-hrp2/sdk/
 - cp -rv RB-ev3rt-hrp2-sdk/ ev3rt-hrp2/sdk/
 - cd ev3rt-hrp2
 - cd cfg
 - make
 - cd ../base-workspace
 - make app=loader
 - cd ../sdk/workspace

script: make app=helloev3
